---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jubiyyzk/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp contact-us.php $DEPLOYPATH
    - /bin/cp about-us.php $DEPLOYPATH
    - /bin/cp services.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH